- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Logistics # DeltaV - Logistics Department replacing Cargo
    min: 18000 # Goob MRP - 5 Hours
  - !type:CharacterDepartmentTimeRequirement
    department: Engineering
    min: 18000 # Goob MRP - 5 Hours
  - !type:CharacterDepartmentTimeRequirement
    department: Medical
    min: 18000 # Goob MRP - 5 Hours
  - !type:CharacterDepartmentTimeRequirement
    department: Security
    min: 18000 # Goob MRP - 5 Hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Epistemics dept time requirement
    department: Epistemics # DeltaV - Epistemics Department replacing Science
    min: 18000 # Goob MRP - 5 Hours
  - !type:CharacterDepartmentTimeRequirement
    department: Command
    min: 72000 # Goob MRP - 20 Hours
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 108000 # Goob MRP - 30 Hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Pacifist
    - Muted
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: Condemned # Goobstation - Nanotrasen owns your soul pal.
      soulOwnedNotDevil: true
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CaptainGear
  subGear:
  - CaptainPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptain
    shoes: ClothingShoesBootsLaceup
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash

- type: startingGear
  id: CaptainPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCaptain
    head: ClothingHeadEnvirohelmCaptain
    gloves: ClothingHandsGlovesCaptain
