- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  requirements:
  - !type:CharacterPlaytimeRequirement
    tracker: JobChef
    min: 7200 # Goob MRP - 2 Hours
  - !type:CharacterPlaytimeRequirement
    tracker: JobBartender
    min: 7200 # Goob MRP - 2 Hours
  - !type:CharacterPlaytimeRequirement
    tracker: JobJanitor
    min: 7200 # Goob MRP - 2 Hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Civilian dept time requirement
    department: Civilian
    min: 36000 # Goob MRP - 10 Hours
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 72000 # Goob MRP - 20 Hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
    - Muted
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - IdrisIncorporated
  weight: 10
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Hydroponics
  - External
  - Cryogenics
  - Lawyer
  - Cargo
  - Boxer
  - Clown
  - Library
  - Mime
  - Musician
  - Reporter
  - Zookeeper
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: HoPGear
  subGear:
  - HoPPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpack
    shoes: ClothingShoesLeather
    id: HoPPDA
    ears: ClothingHeadsetHoP
  storage:
    back:
    - Flash

- type: startingGear
  id: HoPPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoP
    head: ClothingHeadEnvirohelmHoP
    gloves: ClothingHandsGlovesEnviroglovesHoP
