- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 21600
    - !type:CharacterEmployerRequirement
      employers:
      - OrionExpress
      - PMCG
      - NanoTrasen
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  subGear:
  - SalvageSpecialistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetCargo
    pocket1: MiningVoucher

- type: startingGear
  id: SalvageSpecialistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitSalvage
    head: ClothingHeadEnvirohelmSalvage
    gloves: ClothingHandsGlovesEnviroglovesSalvage
    mask: ClothingMaskGasExplorer
    pocket1: MiningVoucher
