- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1800 # goob mrp - 0.5 hours
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hire
  access:
  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
  - Theatre
  - Musician
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer

- type: startingGear
  id: MusicianGear
  subGear:
  - MusicianPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMusician
    back: ClothingBackpack
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService

- type: startingGear
  id: MusicianPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitMusician
    head: ClothingHeadEnvirohelmMusician
    gloves: ClothingHandsGlovesEnviroglovesWhite
